version: '3'
services:
  web:
    image: bassel-math-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7443:5000
    environment:
      - NAME=World
    labels:
      - traefik.http.routers.bassel.rule=Host(`www.bassel.lol`)
      - traefik.http.routers.bassel.entrypoints=http
      - traefik.http.services.bassel.loadbalancer.server.port=5000
    volumes:
      - ./certs:/certs
    command: sh -c "openssl req -newkey rsa:2048 -nodes -keyout /certs/key.pem -x509 -days 365 -out /certs/cert.pem -subj '/CN=www.bassel.lol'"
