version: '3'
services:
  web:
    image: bassel-math-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7443:5000
    environment:
      - NAME=World
    labels:
      - traefik.http.routers.bassel.rule=Host(`www.bassel.lol`)
      - traefik.http.routers.bassel.entrypoints=http
      - traefik.http.services.bassel.loadbalancer.server.port=5000
